import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode><App /></React.StrictMode>
)

// Capture the beforeinstallprompt event so Settings can offer a one-tap install button.
// This must be set up as early as possible — before any async work.
window.__pwaInstallPrompt = null
window.addEventListener('beforeinstallprompt', e => {
  e.preventDefault()
  window.__pwaInstallPrompt = e
  window.dispatchEvent(new CustomEvent('pwa-installable'))
})

window.addEventListener('appinstalled', () => {
  window.__pwaInstallPrompt = null
  window.dispatchEvent(new CustomEvent('pwa-installed'))
})

// Register Vite PWA service worker (generated at build time)
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker
      .register('/sw.js', { scope: '/' })
      .then(reg => {
        console.log('[PWA] Service worker registered:', reg.scope)
      })
      .catch(err => {
        // sw.js is generated by vite-plugin-pwa at build time, not in dev
        if (!import.meta.env.DEV) {
          console.warn('[PWA] Service worker registration failed:', err)
        }
      })
  })
}

